export const API_BaseUrl = "http://localhost:5080/api/"
export const API_UserUrl = "http://localhost:5080/api/User"
export const API_ImgUrl = "http://localhost:5080/api/Image"
export const API_RatingUrl = "http://localhost:5080/api/Rating"
export const API_GeneratorUrl = "http://localhost:5080/api/Generator"